### ISSUE TITLE
There is no indentation when using the plugin

### ISSUE THREAD

**Issue by sharonv** [hkgnp/logseq-rtlblocks-plugin#3]
All blocks show up in the same level

**Comment by giladwo** [comment]
For instance:
![image](https://user-images.githubusercontent.com/25708271/210529053-35821a23-0351-4bb5-b7c4-5cd9cd3789a4.png)

LTR seems to be hardcoded pretty much everywhere (with css classes like `block-children-left-border`), so I guess the best option is to upstream a more direction-agnostic layout.

**Comment by benjypng** [comment]
Apologies, please see the latest version.

**Comment by giladwo** [comment]
> Apologies, please see the latest version.

Seems to be ok now, thanks!

**Comment by sharonv** [comment]
Works fine. thanks
In the app it's aligning on the the first/current graph. 
If you go to the "home" view, and scroll, the rest of the graphs/pages are left aligned though using HEB chars.

**Comment by benjypng** [comment]
> Works fine. thanks In the app it's aligning on the the first/current graph. If you go to the "home" view, and scroll, the rest of the graphs/pages are left aligned though using HEB chars.

You will need to "activate" those blocks by going through the blocks as those are lazy-loaded (I believe), and hence not captured when `custom.js` first activates. If you would like them to be activated right from the start, I suspect https://github.com/sawhney17/logseq-rtl-mode-plugin may be a better option.

**Comment by sharonv** [comment]
For an activated the block your code @hkgnp  is perfect, the challenge that logseq-rtl-mode-plugin does not overcome, is mixed language blocks (which this code does), so having the ability to align the whole block is good but doesn't cover all cases. thanks again 👍
